version: '2'
services:
    batchapp-app:
        image: batchapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://batchapp-postgresql:5432/batchapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    batchapp-postgresql:
        extends:
            file: postgresql.yml
            service: batchapp-postgresql
