version: '2'
services:
    batchapp-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/batchapp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=batchapp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
